/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_redbandit_ndklibnfc_NfcReader */

#ifndef _Included_com_redbandit_ndklibnfc_NfcReader
#define _Included_com_redbandit_ndklibnfc_NfcReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_redbandit_ndklibnfc_NfcReader
 * Method:    jnfc_init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_redbandit_ndklibnfc_NfcReader_jnfc_1init
  (JNIEnv *, jobject);

/*
 * Class:     com_redbandit_ndklibnfc_NfcReader
 * Method:    jnfc_exit
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_redbandit_ndklibnfc_NfcReader_jnfc_1exit
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_redbandit_ndklibnfc_NfcReader
 * Method:    jnfc_version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_redbandit_ndklibnfc_NfcReader_jnfc_1version
  (JNIEnv *, jobject);

/*
 * Class:     com_redbandit_ndklibnfc_NfcReader
 * Method:    jnfc_list_devices
 * Signature: (J[Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_redbandit_ndklibnfc_NfcReader_jnfc_1list_1devices
  (JNIEnv *, jobject, jlong, jobjectArray, jint);

/*
 * Class:     com_redbandit_ndklibnfc_NfcReader
 * Method:    register
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_redbandit_ndklibnfc_NfcReader_register
  (JNIEnv *, jobject);

/*
 * Class:     com_redbandit_ndklibnfc_NfcReader
 * Method:    device_test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_redbandit_ndklibnfc_NfcReader_device_1test
  (JNIEnv *, jobject);


/*WARNING !! Non generated declartion (necessary evil) if you recompile header make sure to copy out and 
paste back */

/* Name: Jprint_debug
 * Desc: Callback used to log messages native to javaland
 *
 */
 
void jprint_debug(char * message);

#ifdef __cplusplus
}
#endif
#endif
