/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_redbandit_utils_JNIInitializer */

#ifndef _Included_com_redbandit_utils_JNIInitializer
#define _Included_com_redbandit_utils_JNIInitializer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_redbandit_utils_JNIInitializer
 * Method:    init_logger
 * Signature: (Lcom/redbandit/utils/JNILogger;)V
 */
JNIEXPORT void JNICALL Java_com_redbandit_utils_JNIInitializer_init_1logger
  (JNIEnv *, jobject, jobject);



#ifdef __cplusplus
}
#endif
#endif
