/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_redbandit_ndklibnfc_NfcReader */

#ifndef _Included_com_redbandit_ndklibnfc_NfcReader
#define _Included_com_redbandit_ndklibnfc_NfcReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_redbandit_ndklibnfc_NfcReader
 * Method:    jnfc_init
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_redbandit_ndklibnfc_NfcReader_jnfc_1init
  (JNIEnv *, jobject);

/*
 * Class:     com_redbandit_ndklibnfc_NfcReader
 * Method:    jnfc_exit
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_redbandit_ndklibnfc_NfcReader_jnfc_1exit
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
